:toc: macro
:toc-title:
:toclevels: 99
= Idioms and Patterns

toc::[]

= Forewords

1. Many of the proposed idioms rely on macros.
"Macros are evil!"
Yes... but they are useful to work around language flaws.
Given the evolution of the language, some of them might well disapear.
For example, CRTP is generally replaced with explicit object parameters in C++23,
hence deprecating the proposed `CRTP_DERIVED` macro.
2. Some of the idioms depend on previously presented idioms, therefore the order is important.
3. Many idioms are bound to C++17 or earlier, and would be simpler or useless with more recent versions.

= Move and Forward

Move and forward idioms are generally implemented with standard functions `std::move()` and `std::forward()`.
Yet, this is not necessary and plain `static_cast`s are enough.
Functions cost more at compile time and possibly pessimize runtime.
Macros can simplify coding:

```cpp
#define MOVE(...) static_cast<std::remove_reference_t<decltype(__VA_ARGS__)>&&>(__VA_ARGS__)
#define FORWARD(...) static_cast<decltype(__VA_ARGS__)&&>(__VA_ARGS__)
```

= Pre-C++20 Member Detection

Until C++20, there are no formal concepts, but it is still possible to `std::enable` functions according to some named requirements.
For example, let's enable a function `f()` for classes which implement methods `begin()` and `end()` returning an iterator to some `int`-convertible type:

```cpp
template <typename T, typename = void>
struct IsIntRange : std::false_type {};

template <typename T>
struct IsIntRange<T, std::void_t<decltype(std::declval<T>().begin()), decltype(std::declval<T>().end())>> :
    std::is_convertible<decltype(*std::declval<T>().begin()), int> {};
    // or simply std::true_type if detecting return type is not relevant

template <typename T>
constexpr bool is_int_range()
{
  return IsIntRange<T>::value; // Sometimes std::decay_t<T> is preferrable to T
}

template <typename T, typename std::enable_if_t<is_int_range<T>()>* = nullptr> // Reduces to void* = nullptr
void f(T& in);
```

Note: With C++20, all of this can be replaced with Concepts.

= Mixin (from above)

Mixins in C++ can be implemented with CRTP:

```cpp
template <typename TDerived>
struct SizeMixin {
  std::size_t size() const
  {
    return std::distance(
      static_cast<const TDerived&>(*this).begin(),
      static_cast<const TDerived&>(*this).end());
  }
};

template <typename TDerived>
struct AdditiveMixin {
  template <typename T>
  TDerived& operator+(const T& rhs)
  {
    auto& derived = static_cast<TDerived&>(*this);
    assert(derived.size() == rhs.size()); // Here provided by SizeMixin via TDerived
    std::transform(derived.begin(), derived.end(), rhs.begin(), [](auto l, auto r) {
        return l + r;
      });
    return derived;
  }
};

template <typename T, typename U, typename std::enable_if_t<are_addable<U, V>()>* = nullptr>
T operator+(T lhs, const U& rhs)
{
  lhs += rhs;
  return lhs;
}

template <typename T>
struct Vector : SizeMixin<Vector<T>>, AdditiveMixin<Vector<T>> { // multiple CRTP
  const T* begin() const;
  const T* end() const;
  T* begin();
  T* end();
  ...
};

Vector<int> u(...);
Vector<int> v(...);
auto w = u + v;
```

Implementation can be simplified with dedicated macros:

```cpp
#define CRTP_CONST_DERIVED static_cast<const TDerived&>(*this)
#define CRTP_DERIVED static_cast<TDerived&>(*this)
```

Note: C++23 introduces explicit object parameters, making implementation of mixins more straightforward,
and eliminating the need for CRTP in most cases.

= Passkey (Restricted Friendship)

Generally, friendship grants access to all the private members of a class.
It is possible to select a set of members only, using a dedicated empty class named a passkey:

```cpp
class Class {
  class FooKey {
    friend class FooAccessor;
    FooKey() {}
  };

  class BarKey {
    friend class BarAccessor;
    BarKey() {}
  };

  void foo(FooKey);

  void bar(BarKey);
};

struct FooAccessor {
  void foo(Class& c)
  {
    return c.foo({});
  }
};

struct BarAccessor {
  void bar(Class& c)
  {
    return c.bar({});
  }
};
```

= Template Specialization Macro

TODO

```cpp
#define FOREACH_SUPPORTED_TYPE(MACRO) \
  MACRO(bool) \
  MACRO(int) \
  MACRO(float)
```

= Virtual Method Template

It is not possible to declare method templates `virtual`.
Yet, when the set of acceptable template parameters is finite, then a workaround can be implemented:

```cpp
struct Interface {
  virtual void method(bool) = 0;
  virtual void method(int) = 0;
  virtual void method(float) = 0;
};

template <typename TDerived>
struct InterfaceImpl : Interface {

  void method(bool a) override
  {
    return CRTP_DERIVED.method_impl(a);
  }

  void method(int a) override
  {
    return CRTP_DERIVED.method_impl(a);
  }

  void method(float a) override
  {
    return CRTP_DERIVED.method_impl(a);
  }
};

struct Implementation : InterfaceImpl<Implementation> {

  template <typename T>
  void method_impl(T a)
  {
    ...
  }
};
```

Given that the contents of `Interface` and `InterfaceImpl` are repetitive, they can be macro-generated:

```cpp
struct Interface {
#define DECLARE_METHOD(T) \
  virtual void method(T) = 0;
FOREACH_SUPPORTED_TYPE(DECLARE_METHOD)
#undef DECLARE_METHOD
};

template <typename TDerived>
struct InterfaceImpl : Interface {
#define DEFINE_METHOD(T) \
  void method(T a) override \
  { \
    return CRTP_DERIVED.method_impl(a); \
  }
FOREACH_SUPPORTED_TYPE(DEFINE_METHOD)
#undef DEFINE_METHOD
};

struct Implementation : InterfaceImpl<Implementation> {

  template <typename T>
  void method_impl(T a)
  {
    ...
  }
};
```
