:toc: macro
:toc-title:
:toclevels: 99
= On Naming

toc::[]

= Introduction

This page focuses specifically on casing, prefixing and postfixing.
The wording is another topic.

In order to decide how to write the various C++ names, we will introduce an equivalence relation based on fundamental principles.
For simplicity, let us introduce early the different equivalence classes.
These terms will be used to group the different items being described:

* Type-equivalent;
* Variable-equivalent.

From the principles and equivalences, we will derive naming rules.
Rules are not a matter of taste; they are absolute and objective.
Whenever possible, the rules MUST be followed.

Later, recommendations are given, motivated by some sense of elegance but not by principles.
In case no other constraints exist, the recommendations SHOULD be followed.

Finally, additional guidelines are simply proposed.
They are useful when open questions remain.

= Fundamental principles

== Consistency Principle: Naming MUST be consistent

All classes must follow the same conventions, all functions must follow the same conventions, and so on.
This is a prerequisite to using any coding standard.

== Standard Compatibility Principle: Code MUST be compatible with the standard and Boost libraries

The standard and Boost libraries are two of the most widely distributed and used libraries, and probably some of the best tested ones, too.
Given that they use the same naming conventions, compatibility with the standard library is sufficient to get compatibility with Boost's.

== Refactoring Invariance Principle: Refactoring MUST NOT require user code changes because of naming

Refactoring is a way of doing *the same thing*, better.
Doing the same thing means using it the same way, from the public interface point of view.

Said otherwise, style alone must not make some refactoring non backward compatible.

= Rules

== Type-equivalence: Namespaces, types and enumerations MUST follow the same naming conventions

From a public API point of view, the following snippets are equivalent.

```cpp
// A. Namespace and static variable
namespace Foo {
  static constexpr int bar;
}

// B. Struct and static data member
struct Foo {
  static constexpr int bar;
};

// C. Class and enumerator
class Foo {
public:
  enum {
    bar
  };
};

// D. Enumeration and enumerator
enum class Foo {
  bar
};

// Works both with A, B, C, and D
constexpr auto FooBar = Foo::bar;
```

From the Refactoring Principle, it follows that namespaces, types and enumerations are equivalent, and must use the same naming conventions.
They can typically be written in `snake_case` or `PascalCase`.

== Variable-equivalence: Enumerators, free functions, methods, variables and public data members MUST follow the same conventions

The previous example already showed that variables, static data members and enumerators are equivalent.
Additionally, we will show that free functions, methods and non static data members are equivalent.
Let us start with the equivalence of free functions and static methods, as well as of static and non-static public data members:

```cpp
// A. Function
namespace Foo {
  static constexpr int bar;
  int baz();
}

// B. Static method
struct Foo {
  static constexpr int bar;
  static int baz();
};

// Works both with A and B
auto foo_bar = Foo::bar;
auto foo_baz = Foo::baz();
```

Then, for static and non static methods:

```cpp
// A. Static method
struct Foo {
  static int bar();
};

// B. Non static method
struct Foo {
  int bar();
};

// Works both with A and B
auto foo_bar = Foo().bar();
```

And finally, for free functions and variables:

```cpp
// A. Function
int bar();

// B. Functor
struct Bar {
  int operator()();
};
Bar bar;

// C. Lambda
auto bar = []() { /* whatever */ };

// Works both with A, B, and C
auto foo = bar();
```

As a conclusion, numerators, free functions, methods, variables and public data members are equivalent and MUST use the same naming conventions.
Their casing MUST be `snake_case`, see below.

== Interfaces, abstract classes and concrete classes MUST follow the same conventions

During some backward compatible refactoring, interfaces may be made abstract classes (simply by adding a concrete method), and abstract classes may be made concrete (simply by providing a default implementation for each virtual method).

The Refactoring Invariance Principle implies that the same naming conventions must be applied (e.g. no `I` or `Abstract` prefix or `Interface` suffix).

By contrast, CRTP classes like mixins can rely on a dedicated naming convention, e.g. require a `Mixin` suffix.

== Variable-equivalent items MUST use `snake_case`

The standard library features services which rely on metaprogramming in order to be compatible with any (possibly user-defined) class.
The only constraint is to follow standard naming conventions (see {cpp}11 Named requirements or {cpp}20 Concepts).
For example, `std::back_inserter` works with classes which provide a method named *precisely* `push_back`.
It follows from the first two Principles that functions (and equivalent identifiers) must use `snake_case`.

Note that the same reasonning *could* apply to classes (and therefore to all the other names), since some nested type names are standardized (like `value_type` or `iterator`).
However, creating compatibility aliases *without any cost* is straightforward (which is not the case with fonctions, even `inline` ones) and comes with very little noise.

```cpp
struct Foo {

  struct Bar;
  template <typename T> struct Baz;
  
  using value_type = Bar;
  using iterator = Baz<value_type>;
  using const_iterator = Baz<value_type const>;
  
  const_iterator begin() const;
  iterator begin();
  const_iterator end() const;
  iterator end();
  
};
```

== Preprocessor macros, and only preprocessor macros, MUST use `ALL_CAPS`

Macros are a distinct language within the language, and must be distinguished from plain {cpp} code for safety reasons.
`ALL_CAPS` case (aka `MACRO_CASE`) is the de facto standard casing in C.
By the Consistency Principle, macros must use `ALL_CAPS` case and other idenfiers must not.

== Only the first letter of an acronyms MAY be capitalized

If all the acronym letters were capitalized, pure identifiers made only of acronyms would be undistiguishable from `ALL_CAPS` (which is reserved for preprocessor macros).

Some standards recommend using this convention except for 2-letter acronyms (e.g. `XmlIOStream`).
However, we consider the Consistency Principle discourages the introduction of such exceptions (e.g. `XmlIoStream`).

= Recommendations

== Functions and classes SHOULD use different casings

In the above example, the intent of `begin()` and `end()` is made even clearer by having different conventions for user-focused and standard-focused names.
Given that user classes are in `PascalCase` in this example, it is indeed absolutely clear that `begin()` is meant to be used with the standard library.

Moreover, having different casings helps readability, e.g.:

```cpp
Foo foo;
// reads better than
foo_type foo;
```

Consequently, the recommendation is to use `snake_case` for function-equivalent identifiers and `PascalCase` for class-equivalent identifiers (`camelCase` would be too exotic and `ALL_CAPS` is already forbidden).

== Identifiers length SHOULD NOT be constrained

Some short identifiers are standard (e.g. `at` or `j`).
Potentially too long identifiers would be a symptom of something else going wrong (e.g. violated Single Responsibility Principle).
Naming conventions do not seem to be the right place to detect such issues.
Moreover, there is no natural bound.

We recommend not limitting identifiers length.

== Concepts SHOULD use the same casing as types

= Proposals

== Use `snake_case` for variable-equivalent items 

== Use `PascalCase` for type-equivalent items

== Prefix concepts with `Any`

== Prefix type template parameters with `T`

== Suffix mixins end with `Mixin`

= Summary
