:toc: macro
:toc-title:
:toclevels: 99
= On Naming

toc::[]

= Introduction

This page focuses specifically on casing, prefixing and postfixing.
The wording is another topic.

In order to decide how to write the various C++ names, we will introduce an equivalence relation based on fundamental principles.

From the principles and equivalences, we will derive naming rules.
Rules are not a matter of taste; they are absolute and objective.
Whenever possible, the rules MUST be followed.

Later, recommendations are given, motivated by some sense of elegance but not by principles.
In case no other constraints exist, the recommendations SHOULD be followed.

Finally, additional guidelines are simply proposed.
They are useful when open questions remain.

= Fundamental principles

== Consistency Principle: Naming MUST be consistent

All classes must follow the same conventions, all functions must follow the same conventions, and so on.
This is a prerequisite to using any coding standard.

== Standard Compatibility Principle: Code MUST be compatible with the standard and Boost libraries

The standard and Boost libraries are two of the most widely distributed and used libraries, and probably some of the best tested ones, too.
Given that they use the same naming conventions, compatibility with the standard library is sufficient to get compatibility with Boost's.

== Refactoring Invariance Principle: Refactoring MUST NOT require user code changes because of naming

Refactoring is a way of doing *the same thing*, better.
Doing the same thing means using it the same way, from the public interface point of view.

Said otherwise, style alone must not make some refactoring non backward compatible.

== Human Brain Principle: Exceptions MUST be exceptional

The coding standard is everywhere and should reduce mental workload instead of increasing it.
Rules will be better applied if they are always applicable.
Special cases and exceptions must therefore be reduced to what is strictly necessary.

= Rules

== Type equivalence: Namespaces, types, type aliases, and enumerations MUST follow the same naming conventions

From a public API point of view, the following snippets are equivalent.

```cpp
// A. Namespace and static variable
namespace Foo {
  static constexpr int bar;
}

// B. Struct and static data member
struct Foo {
  static constexpr int bar;
};

// C. Class and enumerator
class Foo {
public:
  enum {
    bar
  };
};

// D. Enumeration and enumerator
enum class Foo {
  bar
};

// E. Alias and static data member
template <typename T>
struct GFoo {
  static constexpr T bar;
};

using Foo = GFoo<int>;

// Works equivalently with A, B, C, D, and E
constexpr auto foo_bar = Foo::bar;
```

From the Refactoring Principle, it follows that namespaces, types, type aliases, and enumerations are equivalent, and MUST use the same naming conventions.
They can typically be written in `snake_case` or `PascalCase`.

== Variable equivalence: Enumerators, free functions, methods, variables, and public data members MUST follow the same conventions

The previous example already showed that variables, static data members and enumerators are equivalent.
Additionally, we will show that free functions, methods and non static data members are equivalent.
Let us start with the equivalence of free functions and static methods, as well as of static and non-static public data members:

```cpp
// A. Function
namespace Foo {
  static constexpr int bar;
  int baz();
}

// B. Static method
struct Foo {
  static constexpr int bar;
  static int baz();
};

// Works equivalently with A and B
auto foo_bar = Foo::bar;
auto foo_baz = Foo::baz();
```

Then, for static and non static methods:

```cpp
// A. Static method
struct Foo {
  static int bar();
};

// B. Non static method
struct Foo {
  int bar();
};

// Works equivalently with A and B
auto foo_bar = Foo().bar();
```

For free functions and variables:

```cpp
// A. Function
int bar();

// B. Functor
struct Bar {
  int operator()();
};
Bar bar;

// C. Lambda
auto bar = []() { /* whatever */ };

// Works equivalently with A, B, and C
auto foo = bar();
```

As a conclusion, enumerators, free functions, methods, variables, and public data members are equivalent and MUST use the same naming conventions.
Their casing MUST be `snake_case`, see below.

== Interfaces, abstract classes and concrete classes MUST follow the same conventions

During some backward compatible refactoring, interfaces may be made abstract classes (simply by adding a concrete method), and abstract classes may be made concrete (simply by providing a default implementation for each virtual method).

The Refactoring Invariance Principle implies that the same naming conventions must be applied (e.g. no `I` or `Abstract` prefix or `Interface` suffix).

By contrast, CRTP classes like mixins can rely on a dedicated naming convention, e.g. require a `Mixin` suffix.

== Variable-equivalent items MUST use `snake_case`

The standard library features services which rely on metaprogramming in order to be compatible with any (possibly user-defined) class.
The only constraint is to follow standard naming conventions (see {cpp}11 Named requirements or {cpp}20 Concepts).
For example, `std::back_inserter` works with classes which provide a method named *precisely* `push_back`.
It follows from the first two Principles that functions (and equivalent identifiers) must use `snake_case`.

Note that the same reasonning *could* apply to classes (and therefore to all the other names), since some nested type names are standardized (like `value_type` or `iterator`).
However, creating compatibility aliases *without any cost* is straightforward (which is not the case with fonctions, even `inline` ones) and comes with very little noise.

```cpp
struct Foo {

  struct Bar;
  template <typename T> struct Baz;
  
  using value_type = Bar;
  using iterator = Baz<value_type>;
  using const_iterator = Baz<value_type const>;
  
  const_iterator begin() const;
  iterator begin();
  const_iterator end() const;
  iterator end();
  
};
```

== Templates MUST follow their specialization naming conventions

Often, template parameters can be omitted, such that class templates or function templates are equivalent to classes or functions.

```cpp
// A. Class and method templates
template <typename T>
struct Foo {

  Foo(T);

  template <typename TArg>
  int baz(TArg)
};

// B. Class and method
struct Foo {

  Foo(int);

  int baz(int);
};

// Works both with A and B
auto foo = Foo(0);
auto foo_baz = foo.baz(0);
```

== Preprocessor macros, and only preprocessor macros, MUST use `ALL_CAPS`

Macros are a distinct language within the language, and must be distinguished from plain {cpp} code for safety reasons.
`ALL_CAPS` case (aka `MACRO_CASE`) is the de facto standard casing in C.
By the Consistency Principle, macros must use `ALL_CAPS` case and other idenfiers must not.

== Only the first letter of an acronyms MAY be capitalized

If all the acronym letters were capitalized, pure identifiers made only of acronyms would be undistiguishable from `ALL_CAPS` (which is reserved for preprocessor macros).

Some standards recommend using this convention except for 2-letter acronyms (e.g. `XmlIOStream`), arguing that readability is improved.
However, this argument is subjective, and the Consistency and Human Brain Priciples forbid the introduction of such difficult-to-justify exceptions.

= Recommendations

== Functions and classes SHOULD use different casings, thus `snake_case` and `PascalCase`, respectively

In the above example, the intent of `begin()` and `end()` is made clear by having different conventions for user-focused and standard-focused names:
indeed, returning `iterator` (and not `Iterator`) conveys the information the method is standard-compliant.
Given that user classes are in `PascalCase` in this example, it is indeed absolutely clear that `begin()` is meant to be used with the standard library.

Moreover, having different casings helps readability, e.g.:

```cpp
Foo foo;
// reads better than
foo_type foo;
```

Consequently, the recommendation is to use `snake_case` for function-equivalent identifiers and `PascalCase` for class-equivalent identifiers (`camelCase` would be too exotic and `ALL_CAPS` is already forbidden).

== Template parameters should use different conventions than identifiers

Template parameters are not identifiers: they are metaprogramming entities which do not belong the API.
We therefore recommend that they SHOULD use different naming conventions as identifiers.

== Name length SHOULD NOT be constrained

Some short identifiers are standard (e.g. `at` or `j`).
Potentially too long names would be a symptom of something else going wrong (e.g. violated Single Responsibility Principle).
Naming conventions do not seem to be the right place to detect such issues.
Moreover, there is no natural bound.

We recommend not limitting identifiers length.

= Proposals

== Prefix concepts with `Any` and use `PascalCase`

This is a good way of avoiding name clashes.
The C++ standard does not have such rule, which leads to weird names like class `std::iterator` and associated concept `std::input_or_output_iterator`.

Another proposal of the standard commitee is to have short concept names, and longer class names (typically prefixed with `default_`),
assuming that class names should be less frequent in public APIs than concept names.
This is true for standalone developments but generally incompatible with most dependencies.
As an illustration, the standard class `std::allocator` should be renamed as `std::default_allocator`
in order to use `std::allocator` as a concept.
This is not going to happen.
Going with classical class names and a simple prefix for associated concepts is more in line with the Consistency and Human Brain Principles.

== Prefix type template parameters with `T`

This is a good way of distinguishing them from type identifiers, and a very common one.

== Use `PascalCase` for non-type template parameters

This is a good way of distinguishing them from variable identifiers, and a very common one.

== When working with packs, suffix the first parameters with indices and the pack with `s`

This is very readable:

```cpp
template <typename T0, typename T1, typename... Ts>
class Foo;

template <typename TArg0, typename... TArgs>
int bar(TArg0&&, TArgs&&...);
```

== Suffix mixins with `Mixin`, along with template parameter `TDerived`

Mixins are conceptually different types of items than classical base classes.
The CRTP is a common yet confusing name; we prefer the words mixin and derived, which are also understood in other languages.

Example:

```cpp
template <typename T>
concept AnyFoo { ... };

template <typename T, typename TDerived>
```

= Summary

Equivalence classes are:

* Concepts;
* Type-equivalent items: Namespaces, types, template types, type aliases, template type aliases, and enumerations;
* Nested type aliases;
* Variable-equivalent items: Enumerators, free functions, methods, variables, and public data members;
* Type template parameters;
* Non-type template parameters;
* Macros.

Example:

```cpp
#ifndef QUX_FOO_INCLUDED
#define QUX_FOO_INCLUDED

namespace Qux {

template <typename T>
concept AnyFoo = requires(T foo) {
  {foo.baz(0)} -> std::convertible_to<typename T::value_type>;
};

template <typename T, typename TDerived>
struct FooMixin {

  using value_type = T;

  T baz(T p)
  {
    return TDerived::bar + p;
  }
};

template <typename T>
struct GFoo : public FooMixin<T, GFoo<T>> {

  static constexpr int bar = 42;
};

using Foo = GFoo<int>;

template <auto I, AnyFoo TFoo>
typename TFoo::value_type baz(TFoo foo)
{
  return foo.baz(I);
}

} // namespace Qux

#endif
```
